(function(){
  const section=document.getElementById('edital');
  if(!section || document.getElementById('prfAiEditalCard')) return;
  const style=document.createElement('style');
  style.textContent=`#prfAiEditalCard{margin-bottom:16px;background:linear-gradient(145deg,#0d1b30f5,#081321f5);border:1px solid #8b3dff66;box-shadow:0 15px 40px #0006}.prf-ai-title{font-size:18px;font-weight:950}.prf-ai-sub{color:#8da3c0;font-size:12px;line-height:1.5;margin-top:4px}.prf-ai-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.prf-ai-btn{border:1px solid #8b3dff;background:linear-gradient(135deg,#6d28d9,#2878ff);color:#fff;border-radius:10px;padding:10px 14px;font-weight:950;cursor:pointer}.prf-ai-btn.secondary{background:#173c62;border-color:#466887}.prf-ai-btn:disabled{opacity:.55;cursor:wait}#prfAiEditalStatus{margin-top:10px;color:#8da3c0;font-size:12px}.prf-ai-preview{display:none;margin-top:15px;border-top:1px solid #263f5b;padding-top:15px}.prf-ai-preview.show{display:block}.prf-ai-discipline{border:1px solid #29455f;border-radius:10px;padding:11px;margin-bottom:10px;background:#07111f}.prf-ai-discipline-title{font-weight:950;color:#00e5ff;margin-bottom:8px}.prf-ai-topic{display:grid;grid-template-columns:24px 1fr;gap:8px;align-items:start;padding:6px 0;border-top:1px solid #1b3048}.prf-ai-topic input[type=checkbox]{margin-top:7px}.prf-ai-topic-text,.prf-ai-topic-notes{width:100%;background:#07101e;border:1px solid #2b4867;color:#fff;border-radius:7px;padding:8px}.prf-ai-topic-notes{margin-top:5px;color:#9eb2c8;font-size:11px}.prf-ai-footer{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}@media(max-width:650px){.prf-ai-btn{width:100%}.prf-ai-footer{display:grid;grid-template-columns:1fr}}`;
  document.head.appendChild(style);
  const card=document.createElement('div');
  card.className='card';card.id='prfAiEditalCard';
  card.innerHTML=`<div class="section"><div><div class="prf-ai-title">🤖 Importar edital com IA</div><div class="prf-ai-sub">Envie uma foto ou imagem do edital. A IA reconhece disciplinas e tópicos e mostra uma prévia antes de salvar.</div></div></div><div class="prf-ai-actions"><label class="prf-ai-btn" for="prfAiEditalFile">📷 Ler imagem do edital</label><input id="prfAiEditalFile" type="file" accept="image/png,image/jpeg,image/webp" capture="environment" hidden><button class="prf-ai-btn secondary" id="prfAiEditalClear" type="button">↺ Limpar prévia</button></div><div id="prfAiEditalStatus">Nenhuma imagem selecionada.</div><div id="prfAiEditalPreview" class="prf-ai-preview"></div>`;
  section.insertBefore(card,section.firstElementChild);
  const fileInput=document.getElementById('prfAiEditalFile'),status=document.getElementById('prfAiEditalStatus'),preview=document.getElementById('prfAiEditalPreview');
  let result=null;
  const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLowerCase();
  const escHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const reset=()=>{result=null;preview.innerHTML='';preview.classList.remove('show');status.textContent='Nenhuma imagem selecionada.';fileInput.value=''};
  document.getElementById('prfAiEditalClear').onclick=reset;
  function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=2200,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
  function renderPreview(data){result=data;const groups=data?.disciplines||[];if(!groups.length){status.textContent='A IA não encontrou uma estrutura de edital legível.';return}preview.innerHTML=groups.map((d,di)=>`<div class="prf-ai-discipline"><div class="prf-ai-discipline-title">${escHtml(d.name)}</div>${(d.topics||[]).map((t,ti)=>`<label class="prf-ai-topic"><input type="checkbox" checked data-di="${di}" data-ti="${ti}"><span><input class="prf-ai-topic-text" value="${escHtml(t.topic)}" data-field="topic" data-di="${di}" data-ti="${ti}"><textarea class="prf-ai-topic-notes" data-field="notes" data-di="${di}" data-ti="${ti}" placeholder="Observação (opcional)">${escHtml(t.notes||'')}</textarea></span></label>`).join('')}</div>`).join('')+`<div class="prf-ai-footer"><button type="button" class="prf-ai-btn secondary" id="prfAiCancel">Cancelar</button><button type="button" class="prf-ai-btn" id="prfAiConfirm">✅ Confirmar e adicionar ao edital</button></div>`;preview.classList.add('show');document.getElementById('prfAiCancel').onclick=reset;document.getElementById('prfAiConfirm').onclick=confirmImport;status.textContent=`Prévia pronta: ${groups.length} disciplina(s). Revise antes de confirmar.`}
  async function confirmImport(){const boxes=[...preview.querySelectorAll('input[type=checkbox][data-di]')].filter(x=>x.checked);let added=0,skipped=0;for(const box of boxes){const di=+box.dataset.di,ti=+box.dataset.ti,group=result.disciplines[di],topicEl=preview.querySelector(`input[data-field="topic"][data-di="${di}"][data-ti="${ti}"]`),notesEl=preview.querySelector(`textarea[data-field="notes"][data-di="${di}"][data-ti="${ti}"]`),discipline=String(group?.name||'').trim(),topic=String(topicEl?.value||'').trim(),notes=String(notesEl?.value||'').trim();if(!discipline||!topic)continue;let d=db.disciplines.find(x=>norm(x.name)===norm(discipline));if(!d){d={id:uid(),name:discipline,color:'#00e5ff',active:true,weight:1};db.disciplines.push(d)}if(db.syllabus.some(x=>norm(x.discipline)===norm(discipline)&&norm(x.topic)===norm(topic))){skipped++;continue}db.syllabus.push({id:uid(),discipline:d.name,topic,notes,completed:false});added++}if(added||skipped){await persist(`Edital importado: ${added} tópico(s) adicionado(s)${skipped?` • ${skipped} duplicado(s) ignorado(s)`:''}.`);reset()}else alert('Nenhum tópico foi selecionado para adicionar.')}
  fileInput.onchange=async()=>{const file=fileInput.files?.[0];if(!file)return;if(file.size>15*1024*1024){alert('A imagem é muito grande. Escolha uma imagem de até 15 MB.');reset();return}try{status.textContent='⏳ Preparando imagem e enviando para a IA...';const image=await compress(file);const r=await fetch('/api/ai-edital',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível analisar o edital.');renderPreview(d.result)}catch(e){status.textContent='🔴 '+(e.message||'Falha na leitura do edital.');alert(e.message||'Não foi possível ler o edital.')}};
})();
